apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: model-training-steps-
spec:
  entrypoint: main
  templates:
  - name: main
    steps:
    - - name: data-prep
        template: data-prep-step
    - - name: training
        template: training-step
    - - name: evaluation
        template: evaluation-step

  - name: data-prep-step
    nodeSelector:
      hardware: cpu
    container:
      image: python:3.12
      command: ["sh", "-c"]
      args: ["pip install numpy && python -c 'import numpy as np; print(\"Data prep on CPU: array =\", np.array([1,2,3]))'"]

  - name: training-step
    inputs:
      parameters:
      - name: use_gpu
        value: "true"
    nodeSelector:
      hardware: gpu
    container:
      image: nvcr.io/nvidia/cuda:12.0.0-base-ubuntu20.04
      command: ["sh", "-c"]
      args: ["apt-get update && apt-get install -y python3 python3-pip && pip3 install numpy && python3 -c 'import numpy as np; print(\"Training on GPU (param: {{inputs.parameters.use_gpu}}): simulating computation =\", np.sum(np.array([1,2,3])))'"]

  - name: evaluation-step
    nodeSelector:
      hardware: cpu
    container:
      image: python:3.12
      command: ["sh", "-c"]
      args: ["pip install numpy && python -c 'import numpy as np; print(\"Evaluation on CPU: mean =\", np.mean([1,2,3]))'"]